export const datos=[
  {
    name: "Juan",
    lastname: "Perez",
    cmp: "123456",
    celular: "987654321",
    trayectoria: "lorem ipsum",
    especialidad: "Cardiologia",
    sexo: "2",
    servicio: ["transplante", "cirugia", "resonancia"],
    hospital: ["San Juan de Dios", "San Martin", "San Juan de Dios"],
  },
  {
    name: "Maria",
    lastname: "Gutierrez",
    cmp: "163456",
    celular: "987622321",
    trayectoria: "lorem ipsum",
    especialidad: "Cardiologia",
    sexo: "1",
    servicio: ["transplante", "cirugia", "resonancia"],
    hospital: ["San Juan de Dios", "San Martin", "San Juan de Dios"], 
  },
  {
    name: "Pedro",
    lastname: "Suarez",
    cmp: "127456",
    celular: "983354321",
    trayectoria: "lorem ipsum",
    especialidad: "Cardiologia",
    sexo: "2",
    servicio: ["transplante", "cirugia", "resonancia"],
    hospital: ["San Juan de Dios", "San Martin", "San Juan de Dios"],
  },
  {
    name: "Maria",
    lastname: "Quispe",
    cmp: "127556",
    celular: "983354321",
    trayectoria: "lorem ipsum",
    especialidad: "Pediatria",
    sexo: "1",
    servicio: ["transplante", "cirugia", "resonancia"],
    hospital: ["San Juan de Dios", "San Martin", "San Juan de Dios"],
  }
]